{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.ack.aws.accountID | int }}:role/{{ include "app.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
