---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ephemeral-demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # annotations:
  #   argocd-image-updater.argoproj.io/write-back-method: git
  #   argocd-image-updater.argoproj.io/image-list: app=573010787783.dkr.ecr.eu-central-1.amazonaws.com/test-rds-proxy:*
  #   argocd-image-updater.argoproj.io/app.update-strategy: latest
  #   argocd-image-updater.argoproj.io/app.allow-tags: regexp:^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
  #   argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
  #   argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
  #   notifications.argoproj.io/subscribe.on-deployed.slack: argo-cd
spec:
  project: default
  revisionHistoryLimit: 5
  sources:
    - repoURL: https://github.com/davejfranco/ephemeral-ack-gitops-demo.git
      path: helm/app
      targetRevision: develop
      helm:
        releaseName: app-demo
        valuesObject:
          image:
            repository: nginx
            tag: 1.25.5-alpine
          ack:
            enable: false
        #valueFiles:
        #  - ../dev-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
